//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;


using BRIMS.EmailAlerts.BusinessLogic.Alerts.BankExposures;
using BRIMS.EmailAlerts.BusinessLogic.Alerts.BrokerExposureAlerts;
using BRIMS.EmailAlerts.BusinessLogic.Alerts.RBALimitAlerts;
using BRIMS.EmailAlerts.BusinessLogic.Alerts.TransactionEmailAlerts;
using BRIMS.EmailAlerts.BusinessLogic.Alerts.UmbrellaAlerts;
using BRIMS.EmailAlerts.BusinessLogic.Configuration;
using BRIMS.EmailAlerts.BusinessLogic.Email;
using BRIMS.EmailAlerts.BusinessLogic.System;

namespace BRIMS.EmailAlerts.BusinessLogic.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BRIMSObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BRIMSEntities object using the connection string found in the 'BRIMSEntities' section of the application configuration file.
        /// </summary>
        public BRIMSObjectContext() : base("name=BRIMSEntities", "BRIMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BRIMSEntities object.
        /// </summary>
        public BRIMSObjectContext(string connectionString) : base(connectionString, "BRIMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BRIMSEntities object.
        /// </summary>
        public BRIMSObjectContext(EntityConnection connection) : base(connection, "BRIMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion

    
    
}
